codec:
  quant_type: N00677
  encoder_path: third_party/pcc_codec/bin/gpcc/tmc3_m73385
  decoder_path: third_party/pcc_codec/bin/gpcc/tmc3_m73385
  encode_config_path: third_party/pcc_codec/cfg/gpcc/mpeg151/m73385_octree-predlift/Combined_Predlift/r02/encoder.cfg
  decode_config_path: third_party/pcc_codec/cfg/gpcc/mpeg151/m73385_octree-predlift/Combined_Predlift/r02/decoder.cfg

  use_sh0_ycbcr: true
  use_shN_ycbcr: true
  use_quats_norm: true
  use_quats_posi_w: true

  color_standard: BT470