codec: 
  video_codec_type: hm
  encoder_path: third_party/video_codec/bin/hm_encoder
  decoder_path: third_party/video_codec/bin/hm_decoder
  encode_config_path: third_party/video_codec/cfg/hm/encoder_randomaccess_main_rext.cfg
  decode_config_path: null

  sort_type: plas

  qp_config:
    means_l: -1
    means_u: -1
    opacities: 10
    quats_w: 16
    quats_xyz: 16
    scales: 16
    sh0: 10
    shN_sh1: 22
    shN_sh2: 28
    shN_sh3: 34

  bit_depth_config:
    means_l: 10
    means_u: 10
    opacities: 10
    quats: 10
    scales: 10
    sh0: 10
    shN: 10

  pix_fmt_config:
    means_l: yuv444p
    means_u: yuv444p
    opacities: yuv400p
    quats_w: yuv400p
    quats_xyz: yuv444p
    scales: yuv444p
    sh0: yuv444p
    shN: yuv444p