codec: 
  video_codec_type: hm
  encoder_path: third_party/video_codec/bin/hm_encoder
  decoder_path: third_party/video_codec/bin/hm_decoder
  encode_config_path: third_party/video_codec/cfg/hm/encoder_randomaccess_main_rext.cfg
  decode_config_path: null

  use_sh0_ycbcr: true
  use_shN_ycbcr: true
  use_means_log: true
  use_quats_norm: true

  quant_per_channel: true
  quant_shN_per_channel: true

  sort_type: plas

  qp_config:
    means_l: -1
    means_u: -1
    opacities: 17
    quats_w: 2
    quats_xyz: 2
    scales: 7
    sh0: 7
    shN_sh1: 12
    shN_sh2: 22
    shN_sh3: 27

  bit_depth_config:
    means_l: 8
    means_u: 8
    opacities: 10
    quats: 10
    scales: 10
    sh0: 10
    shN: 10

  pix_fmt_config:
    means_l: yuv444p
    means_u: yuv444p
    opacities: yuv400p
    quats_w: yuv400p
    quats_xyz: yuv444p
    scales: yuv444p
    sh0: yuv444p
    shN: yuv444p